ALTER TABLE GStudent MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE GStudent MODIFY version INT DEFAULT 0;

ALTER TABLE GClassroom MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE GClassroom MODIFY version INT DEFAULT 0;

ALTER TABLE GStudies MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE GStudies MODIFY version INT DEFAULT 0;

ALTER TABLE GUser MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE GUser MODIFY version INT DEFAULT 0;

